---@brief [[
---*comment-nvim.txt*    For Neovim version 0.7           Last change: 2021 July 11
---
---     _____                                     _                _
---    / ____/                                   / /              (_)
---   / /     ___  _ __ ___  _ __ ___   ___ _ __ / /_   _ ____   ___ _ __ ___
---   / /    / _ \/ '_ ` _ \/ '_ ` _ \ / _ \ '_ \/ __/ / '_ \ \ / / / '_ ` _ \
---   / /___/ (_) / / / / / / / / / / /  __/ / / / /_ _/ / / \ V // / / / / / /
---    \_____\___//_/ /_/ /_/_/ /_/ /_/\___/_/ /_/\__(_)_/ /_/\_/ /_/_/ /_/ /_/
---
---                    · Smart and Powerful comment plugin ·
---
---@brief ]]

---@toc comment.contents

---@mod comment-nvim Introduction
---@brief [[
---Comment.nvim is a smart and powerful comment plugin for neovim. It supports
---dot-repeat, counts, line ('//') and block ('/* */') comments, and can be used
---with motion and text-objects. It has native integration with tressitter to
---support embedded filetypes like html, vue, markdown with codeblocks etc.
---
---Comment.nvim uses |g@| and |Operator-pending-mode| to be able to easily comment
---and to support dot-repeat. Following is the brief architecture of the plugin
---
--->
--- - START (keybinding or API)
---
--- - Determine the region using marks, changed text |'[| |']| or visual |'>| |'<|
---
--- - Pick commentstring either linewise/blockwise from one of the following places
---     1. pre_hook (if string is returned)
---     2. stored inside the plugin (with the help of treesitter)
---     3. vim.bo.commentstring
---
--- - Parse commentstring, returns LHS and RHS of commentstring
---
--- >> Every is_comment check is made using the commentstring from the above step
---
--- >> If `gc` is used on the current line i.e., `gc3w` then use blockwise
---
--- - If linewise
---     1. if every line is commented
---         1.1 uncomment
---
---     2. else
---         2.1 find the column no. to start the comment from (indentation)
---         2.2 comment
---
--- - If blockwise
---     1. if the first line or start of the block is commented with LHS
---        and the last line or end of the block is commented with RHS
---        1.1 uncomment
---
---     2. else
---         2.1 Prepend the LHS into the first line
---         2.2 Append the RHS into the last line
---
---     >> In visual block, we can't preprend or append, so in this case we need
---     >> to slice and concat the line, putting RHS and LHS of commentstring into
---     >> right place when doing comment and removing LHS and RHS when uncomment
---
--- - END
---<
---@brief ]]

---@tag comment.commentstring
---@brief [[
---Comment.nvim picks commentstring, either linewise/blockwise, from one of the
---following places
---
--- 1. 'pre_hook'
---       If a string is returned from this function then it will be used for
---       (un)commenting. See |comment.config|
---
--- 2. |comment.ft|
---       Using the commentstring table inside the plugin (using treesitter).
---       Fallback to |commentstring|, if not found.
---
--- 3. |commentstring| - Neovim's native commentstring for the filetype
---
---Although Comment.nvim supports native 'commentstring' but unfortunately it has
---the least priority. The caveat with this approach is that if someone sets the
---`commentstring`, without returning it, from the 'pre_hook' and the current
---filetype also exists in the |comment.ft| then the commenting will be done using
---the string in |comment.ft| instead of using 'commentstring'. To override this
---behavior, you have to manually return the 'commentstring' from 'pre_hook'.
---@brief ]]

---@mod comment.usage Usage
---@brief [[
---Before using the plugin, you need to call the `setup()` function to create the
---default mappings. If you want, you can also override the default configuration
---by giving it a partial 'comment.config.Config' object, it will then be merged
---with the default config.
---@brief ]]

local C = {}

---Configures the plugin
---@param config? CommentConfig User configuration
---@return CommentConfig _ Returns the mutated config
---@see comment.config
---@usage [[
---require('Comment').setup({
---    ignore = '^$',
---    toggler = {
---        line = '<leader>cc',
---        block = '<leader>bc',
---    },
---    opleader = {
---        line = '<leader>c',
---        block = '<leader>b',
---    },
---})
---@usage ]]
function C.setup(config)
    return require('Comment.api').setup(config)
end

return C
